- hosts: all
  become: yes
  tasks:
    - name: Update repos and upgrade
      apt:
        update_cache: yes
        upgrade: yes

# ---
# # This section is only for the webserver(s)
# - hosts: http
#   become: yes
#   tasks:


# ---
# # This section is only for the sqlserver
# - hosts: sql
#   become: yes
#   tasks: